### ISSUE TITLE
Add a mapping save and load from mapping functions

### ISSUE THREAD

**Issue by jennyfothergill** [cmelab/grits#12]
In any workflow that might actually *use* grits, we would need to be able to save and reload the mapping:
1. Create CG_Compound
2. Save to simulation input format (e.g., gsd)
3. Run simulation
4. Load new structure from simulation output
5. Load mapping
6. Backmap!

**Comment by mikemhenry** [comment]
A quick thought:

If performance is important, then a binary format would be better than text!
