### ISSUE TITLE
speed up and scale up!

### ISSUE THREAD

**Issue by jennyfothergill** [cmelab/grits#16]
grits is painfully slow on real simulation morphologies...
- [x] use freud clustering? save doing the same work on a system of identical molecules
- [x] move away from mbuild compound? hierarchical nature not needed, we could use a simpler faster data structure

**Comment by chrisjonesBSU** [comment]
For reference, how long is it currently taking?  I tested out a few larger systems (440,000 atoms) using the freud clustering approach in the polymer utils PR, and it takes about 0.2 - 0.5 seconds to go from an atomistic gsd to CG gsd for a single frame (depending on the degree of coarse graining).  This is still technically using mbuild to generate the CG system, then saving to .gsd. I'm sure it would be quicker to use a gsd writer directly and skip mbuild.

**Comment by jennyfothergill** [comment]
I think it's the smarts matching that is taking so long. I plan to use freud cluster module to break things up and then use smarts matching on only one section.
