### ISSUE TITLE
Idea: fixed-index mapping

### ISSUE THREAD

**Issue by erjank** [cmelab/grits#68]
If we knew mapping between detailed and coarse representations were the same 3 atoms (determined by index order. For example, the ath, bth, and cth atoms in the middle ring of perylene) we could use that mapping to get around hard-to-come-up-with SMILES strings

**Comment by chrisjonesBSU** [comment]
Is this what we already have with the `mapping` parameter in `CG_Compound` and `CG_System`?  This lets you set your atom-to-bead mapping manually without having to write a smiles string.

```
    mapping : dict or path, default None
        Either a dictionary or path to a json file of a dictionary. Dictionary
        keys contain desired bead name and SMARTS string specification of that
        bead and values containing list of tuples of atom indices::

            mapping = {"_B...c1sccc1": [(0, 4, 3, 2, 1), ...]}
```

This would let you manually define your mapping if you want to use some algorithm to generate a list of lists based on known info about your molecules/beads.

**Comment by chrisjonesBSU** [comment]
The doc strings for the `mapping` parameter are a bit confusing, I don't think you really need the smiles string, or you could at least put a place holder `str` there. Nothing ends up happening with it except for setting the `Bead.smarts` attribute which isn't ever used anywhere.

**Comment by erjank** [comment]
Oh, likely! Yeah, this looks like a small docstring update would provide a lot of clarity.
